name: build
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up development Docker Buildx
        id: development_builder
        uses: docker/setup-buildx-action@v1
