name: build
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up development Docker Buildx
        id: development_builder
        uses: docker/setup-buildx-action@v1

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      -
        name: Build testing container
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.development_builder.outputs.name }}
          target: development
          load: true
          tags: travelperk-http-python-testing:latest
      - 
        name: Run tests
        uses: addnab/docker-run-action@v1
        with:
          image: travelperk-http-python-testing:latest
          shell: sh 
          run: sh /app/run_tests_ci ${{ github.sha }} ${{ secrets.CODECOV_TOKEN }}
